import type { StylesConfig } from 'react-select'

export function buildSelectStyles(isDark: boolean, { solidBg = false } = {}): StylesConfig<any, false> {
  return {
    control: (base, _state) => ({
      ...base,
      background: solidBg ? 'var(--bg-panel)' : 'transparent',
      borderColor: 'transparent',
      boxShadow: 'none',
      minHeight: 28,
      height: 28,
      borderRadius: 6,
      fontSize: 11,
      cursor: 'pointer',
      transition: 'background 0.15s ease, border-color 0.15s ease',
      '&:hover': { background: 'var(--bg-hover)', borderColor: 'transparent' },
    }),
    valueContainer:      (base) => ({ ...base, height: 28, padding: '0 8px', flexWrap: 'nowrap', display: 'flex', alignItems: 'center' }),
    indicatorsContainer: (base) => ({ ...base, height: 28 }),
    singleValue:         (base) => ({ ...base, color: 'var(--text-primary)',   fontSize: 11, margin: 0, lineHeight: 1 }),
    placeholder:         (base) => ({ ...base, color: 'var(--text-secondary)', fontSize: 11, margin: 0, lineHeight: 1 }),
    input:               (base) => ({ ...base, color: 'var(--text-primary)',   fontSize: 11, margin: 0, padding: 0, lineHeight: 1 }),
    indicatorSeparator:  ()    => ({ display: 'none' }),
    dropdownIndicator: (base, state) => ({
      ...base,
      padding: '0 6px',
      color: state.isFocused || state.selectProps.menuIsOpen ? 'var(--text-primary)' : 'var(--text-secondary)',
      transform: state.selectProps.menuIsOpen ? 'rotate(180deg)' : 'rotate(0deg)',
      transition: 'transform 0.2s ease, color 0.15s ease',
      '&:hover': { color: 'var(--text-primary)' },
    }),
    clearIndicator: (base) => ({ ...base, padding: '0 4px', color: 'var(--text-secondary)', '&:hover': { color: '#e10600' } }),
    menu: (base) => ({
      ...base,
      background: 'var(--bg-menu)',
      border: '1px solid var(--border)',
      borderRadius: 6,
      boxShadow: '0 8px 32px rgba(0,0,0,0.6)',
      zIndex: 9999,
      marginTop: 4,
      overflow: 'hidden',
    }),
    menuPortal: (base) => ({ ...base, zIndex: 9999 }),
    menuList:   (base) => ({ ...base, padding: 4 }),
    option: (base, state) => ({
      ...base,
      background: state.isSelected ? 'var(--border-focus)' : state.isFocused ? (isDark ? 'rgba(255,255,255,0.12)' : 'var(--bg-hover)') : 'transparent',
      color: state.isSelected ? '#fff' : 'var(--text-primary)',
      fontSize: 11,
      borderRadius: 4,
      padding: '5px 8px',
      cursor: 'pointer',
      transition: 'background 0.1s',
      '&:active': { background: 'var(--border-focus)' },
    }),
  }
}
