// This file is auto-generated by telemetry-mapper/update_app.py. Do not edit manually.
import track0 from '../assets/maps/track_0.json'
import track2 from '../assets/maps/track_2.json'
import track3 from '../assets/maps/track_3.json'
import track4 from '../assets/maps/track_4.json'
import track5 from '../assets/maps/track_5.json'
import track6 from '../assets/maps/track_6.json'
import track7 from '../assets/maps/track_7.json'
import track9 from '../assets/maps/track_9.json'
import track10 from '../assets/maps/track_10.json'
import track11 from '../assets/maps/track_11.json'
import track12 from '../assets/maps/track_12.json'
import track13 from '../assets/maps/track_13.json'
import track14 from '../assets/maps/track_14.json'
import track15 from '../assets/maps/track_15.json'
import track16 from '../assets/maps/track_16.json'
import track17 from '../assets/maps/track_17.json'
import track19 from '../assets/maps/track_19.json'
import track20 from '../assets/maps/track_20.json'
import track26 from '../assets/maps/track_26.json'
import track27 from '../assets/maps/track_27.json'
import track29 from '../assets/maps/track_29.json'
import track30 from '../assets/maps/track_30.json'
import track31 from '../assets/maps/track_31.json'
import track32 from '../assets/maps/track_32.json'
import track39 from '../assets/maps/track_39.json'
import track40 from '../assets/maps/track_40.json'
import track41 from '../assets/maps/track_41.json'

export interface MapTransform {
  min_x: number
  min_z: number
  scale: number
  off_x: number
  off_z: number
}

export interface TrackMapData {
  track_id:       number
  track_name:     string
  circuit_name:   string
  track_length_m: number
  view_box:       { width: number; height: number }
  rotation_deg:   number
  transform:      MapTransform
  sectors:        Array<{ index: number; points: [number, number][] }>
  drs_zones:      Array<{
    start:        [number, number]
    end:          [number, number]
  }>
  // Straight Line Mode (2026) zones — dry- and wet-weather variants. Same
  // {start,end} shape as DRS; the polyline is re-derived from the centerline.
  slm_dry?:       Array<{ start: [number, number]; end: [number, number] }>
  slm_wet?:       Array<{ start: [number, number]; end: [number, number] }>
  speed_traps:    [number, number][]
  start_finish:   [number, number] | null
}

// Add new maps here as they are generated by convert_track.py
export const TRACK_MAPS: Record<number, TrackMapData> = {
  0: track0 as unknown as TrackMapData,
  2: track2 as unknown as TrackMapData,
  3: track3 as unknown as TrackMapData,
  4: track4 as unknown as TrackMapData,
  5: track5 as unknown as TrackMapData,
  6: track6 as unknown as TrackMapData,
  7: track7 as unknown as TrackMapData,
  9: track9 as unknown as TrackMapData,
  10: track10 as unknown as TrackMapData,
  11: track11 as unknown as TrackMapData,
  12: track12 as unknown as TrackMapData,
  13: track13 as unknown as TrackMapData,
  14: track14 as unknown as TrackMapData,
  15: track15 as unknown as TrackMapData,
  16: track16 as unknown as TrackMapData,
  17: track17 as unknown as TrackMapData,
  19: track19 as unknown as TrackMapData,
  20: track20 as unknown as TrackMapData,
  26: track26 as unknown as TrackMapData,
  27: track27 as unknown as TrackMapData,
  29: track29 as unknown as TrackMapData,
  30: track30 as unknown as TrackMapData,
  31: track31 as unknown as TrackMapData,
  32: track32 as unknown as TrackMapData,
  39: track39 as unknown as TrackMapData,
  40: track40 as unknown as TrackMapData,
  41: track41 as unknown as TrackMapData,
}
